// <auto-generated />
using System;
using DAL.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(FacilityBookingDbContext))]
    [Migration("20260205015417_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("CheckInImages")
                        .HasColumnType("text")
                        .HasColumnName("check_in_images");

                    b.Property<string>("CheckInNote")
                        .HasColumnType("text")
                        .HasColumnName("check_in_note");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<string>("CheckOutImages")
                        .HasColumnType("text")
                        .HasColumnName("check_out_images");

                    b.Property<string>("CheckOutNote")
                        .HasColumnType("text")
                        .HasColumnName("check_out_note");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("EstimatedAttendees")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_attendees");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("text")
                        .HasColumnName("special_requirements");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending_Approval")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("text")
                        .HasColumnName("issue_description");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<bool>("ReportIssue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("report_issue");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("booking_feedback", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("campus_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("CampusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "C0001",
                            Address = "Lô E2a-7, Đường D1, Khu Công nghệ cao, P.Long Thạnh Mỹ, Tp. Thủ Đức, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(6384),
                            Email = "daihocfpt@fpt.edu.vn",
                            Name = "FPTU HCM Campus",
                            PhoneNumber = "028 7300 5588",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            CampusId = "C0002",
                            Address = "Số 1 Lưu Hữu Phước, Đông Hoà, Dĩ An, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(6387),
                            Email = "nvhsv@fpt.edu.vn",
                            Name = "Nhà Văn Hóa Sinh Viên",
                            PhoneNumber = "028 7300 5589",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(6388)
                        });
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("facility_id");

                    b.Property<string>("Amenities")
                        .HasColumnType("text")
                        .HasColumnName("amenities");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("campus_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("floor_number");

                    b.Property<int>("MaxConcurrentBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("max_concurrent_bookings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("FacilityId");

                    b.HasIndex("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("TypeId");

                    b.ToTable("facility", (string)null);

                    b.HasData(
                        new
                        {
                            FacilityId = "F00001",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5775),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A101",
                            RoomNumber = "A101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5775)
                        },
                        new
                        {
                            FacilityId = "F00002",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5779),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A102",
                            RoomNumber = "A102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5780)
                        },
                        new
                        {
                            FacilityId = "F00003",
                            CampusId = "C0001",
                            Capacity = 15,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5783),
                            Description = "Phòng họp nhỏ",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B201",
                            RoomNumber = "B201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5783)
                        },
                        new
                        {
                            FacilityId = "F00004",
                            CampusId = "C0001",
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5785),
                            Description = "Phòng họp vừa",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B202",
                            RoomNumber = "B202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5786)
                        },
                        new
                        {
                            FacilityId = "F00005",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5788),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C301",
                            RoomNumber = "C301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5788)
                        },
                        new
                        {
                            FacilityId = "F00006",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5791),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C302",
                            RoomNumber = "C302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5798)
                        },
                        new
                        {
                            FacilityId = "F00007",
                            CampusId = "C0001",
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5800),
                            Description = "Sân bóng rổ ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Sân bóng rổ",
                            RoomNumber = "Court1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5800)
                        },
                        new
                        {
                            FacilityId = "F00008",
                            CampusId = "C0001",
                            Capacity = 80,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5803),
                            Description = "4 sân cầu lông",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 4,
                            Name = "Sân cầu lông",
                            RoomNumber = "Court2",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5803)
                        },
                        new
                        {
                            FacilityId = "F00011",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5898),
                            Description = "Phòng sinh hoạt câu lạc bộ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng N101",
                            RoomNumber = "N101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5900)
                        },
                        new
                        {
                            FacilityId = "F00012",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5903),
                            Description = "Phòng sinh hoạt câu lạc bộ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng N102",
                            RoomNumber = "N102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5903)
                        },
                        new
                        {
                            FacilityId = "F00013",
                            CampusId = "C0002",
                            Capacity = 15,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5906),
                            Description = "Phòng họp Ban chủ nhiệm",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp NVHSV 201",
                            RoomNumber = "N201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5907)
                        },
                        new
                        {
                            FacilityId = "F00014",
                            CampusId = "C0002",
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5909),
                            Description = "Phòng họp CLB",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp NVHSV 202",
                            RoomNumber = "N202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5909)
                        },
                        new
                        {
                            FacilityId = "F00015",
                            CampusId = "C0002",
                            Capacity = 20,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5912),
                            Description = "Phòng sản xuất nội dung",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Media NVHSV",
                            RoomNumber = "N301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5912)
                        },
                        new
                        {
                            FacilityId = "F00016",
                            CampusId = "C0002",
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5914),
                            Description = "Phòng tập nhạc, ca hát",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Âm nhạc",
                            RoomNumber = "N302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5915)
                        },
                        new
                        {
                            FacilityId = "F00017",
                            CampusId = "C0002",
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5917),
                            Description = "Sân khấu tổ chức sự kiện",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 1,
                            Name = "Sân khấu ngoài trời",
                            RoomNumber = "Stage1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5917)
                        },
                        new
                        {
                            FacilityId = "F00018",
                            CampusId = "C0002",
                            Capacity = 50,
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5919),
                            Description = "Khu vực nướng ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Khu vực BBQ",
                            RoomNumber = "BBQ1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 935, DateTimeKind.Utc).AddTicks(5920)
                        });
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("DefaultAmenities")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int?>("TypicalDurationHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("TypeId");

                    b.ToTable("facility_type", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = "FT0001",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4647),
                            Description = "Phòng học lý thuyết",
                            Name = "Phòng học",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4648)
                        },
                        new
                        {
                            TypeId = "FT0002",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4685),
                            Description = "Phòng họp",
                            Name = "Phòng họp",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4686)
                        },
                        new
                        {
                            TypeId = "FT0003",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4687),
                            Description = "Phòng máy tính",
                            Name = "Phòng máy tính",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4688)
                        },
                        new
                        {
                            TypeId = "FT0004",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4689),
                            Description = "Sân thể thao",
                            Name = "Sân thể thao",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 571, DateTimeKind.Utc).AddTicks(4690)
                        });
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("notification_id");

                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unread")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserId1")
                        .HasColumnType("character varying(6)");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("RoleId");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "RL0001",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(3934),
                            RoleName = "Sinh viên",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(3934)
                        },
                        new
                        {
                            RoleId = "RL0002",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(3936),
                            RoleName = "Giảng viên",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(3937)
                        },
                        new
                        {
                            RoleId = "RL0003",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(3938),
                            RoleName = "Quản trị viên cơ sở vật chất",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 570, DateTimeKind.Utc).AddTicks(3938)
                        });
                });

            modelBuilder.Entity("DAL.Models.SystemSettings", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("setting_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("SettingKey");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("email_verification_code");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_code_expiry");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IsVerify")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("is_verify");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_code_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "U00001",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 689, DateTimeKind.Utc).AddTicks(2659),
                            Email = "student@fpt.edu.vn",
                            FullName = "Nguyễn Văn A",
                            IsVerify = "Unverified",
                            Password = "$2a$11$Gd1Ho7C98hbEHDavyPYR.uFXlJq5Qto1Z/Yia0QHSgNGrBaiv9d2.",
                            RoleId = "RL0001",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 689, DateTimeKind.Utc).AddTicks(2666),
                            UserName = "studentA"
                        },
                        new
                        {
                            UserId = "U00002",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 811, DateTimeKind.Utc).AddTicks(1627),
                            Email = "lecturer@fe.edu.vn",
                            FullName = "Trần Thị B",
                            IsVerify = "Unverified",
                            Password = "$2a$11$RPLPn4CKfWWlqIhvuzkPmu.tbAdG6rTRTYm7Xsr1rPWaMMNSDoHdO",
                            RoleId = "RL0002",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 811, DateTimeKind.Utc).AddTicks(1633),
                            UserName = "lecturerB"
                        },
                        new
                        {
                            UserId = "U00003",
                            CreatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 932, DateTimeKind.Utc).AddTicks(9572),
                            Email = "admin@fpt.edu.vn",
                            FullName = "Quản trị viên hệ thống",
                            IsVerify = "Unverified",
                            Password = "$2a$11$DJehRtzWQhjVZ3U78nol1eSJ9yf342xyAvx/GsyLSpzfXI4yX78Ha",
                            RoleId = "RL0003",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 2, 5, 1, 54, 16, 932, DateTimeKind.Utc).AddTicks(9581),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.HasOne("DAL.Models.User", "Approver")
                        .WithMany("ApprovedBookings")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithOne("Feedback")
                        .HasForeignKey("DAL.Models.BookingFeedback", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Facilities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedFacilities")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("FacilityManager");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DAL.Models.BookingFeedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId1");

                    b.Navigation("Booking");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("ApprovedBookings");

                    b.Navigation("Bookings");

                    b.Navigation("ManagedFacilities");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
